services:
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - TZ=Europe/Paris
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  redis:
    image: redis:7-alpine

  worker:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    command: celery -A celery_app:app worker --loglevel=info

  beat:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    command: celery -A celery_app:app beat --loglevel=info
