services:
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db
  redis:
    image: redis:7-alpine
  worker:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - db
    command: celery -A celery_app:app worker --loglevel=info
  beat:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - db
    command: celery -A celery_app:app beat --loglevel=info
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petroleum
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
